name = "placeholders-dev"
type = "webpack"
account_id = "d9c4a171c4a0d0a8e6f8204ae9ba0638"
zone_id = "cd7d068de3012345da9420df9514dad0"
workers_dev = true

[site]
bucket = "./public"
entry-point = "./workers-site"
